[package]
name = "shareclick"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "shareclick"
path = "src/main.rs"

[dependencies]
anyhow = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rdev = { version = "0.5", features = ["unstable_grab"] }
enigo = "0.6"
x25519-dalek = { version = "2", features = ["getrandom"] }
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"